services:
  db:
    image: postgres:16.2
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transactions

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  db_data:
