name: Deploy to Fly.io

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_dispatch:
    inputs:
      # we use a boolean input to deploy to fly io
      deploy:
        description: 'Deploy to Fly.io'
        required: false
        type: boolean
        default: false
  release:
    types:
      - released

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Fly.io Deploy
    runs-on: ubuntu-latest
    # only run if it is a release
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
            go-version: '1.22'
      - name: Build
        run: make build
      - name: Test
        run: make test

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
